# Generated by Django 6.1 on 2026-08-25 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('click_power', 'Сила клика'), ('auto_clicker', 'Автокликер'), ('crit_chance', 'Шанс крита'), ('max_energy', 'Максимум энергии')], max_length=20, unique=True, verbose_name='Тип апгрейда')),
                ('base_cost', models.PositiveBigIntegerField(verbose_name='Базовая цена')),
                ('cost_multiplier', models.FloatField(default=1.5, verbose_name='Множитель цены')),
                ('effect_per_level', models.FloatField(verbose_name='Эффект за уровень')),
            ],
            options={
                'verbose_name': 'Апгрейд',
                'verbose_name_plural': 'Апгрейды',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveBigIntegerField(default=0, verbose_name='Монеты')),
                ('total_clicks', models.PositiveBigIntegerField(default=0, verbose_name='Всего кликов')),
                ('energy', models.PositiveIntegerField(default=100, verbose_name='Энергия')),
                ('max_energy_level', models.PositiveIntegerField(default=0, verbose_name='Уровень апгрейда энергии')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Последний визит')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='core.profile', verbose_name='Профиль')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.upgrade', verbose_name='Апгрейд')),
            ],
            options={
                'verbose_name': 'Апгрейд игрока',
                'verbose_name_plural': 'Апгрейды игроков',
                'constraints': [models.UniqueConstraint(fields=('profile', 'upgrade'), name='unique_profile_upgrade')],
            },
        ),
    ]
