# Generated by Django 6.1 on 2026-08-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_upgrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('mu', models.FloatField(verbose_name='Дрейф (за секунду)')),
                ('sigma', models.FloatField(verbose_name='Волатильность (за √секунды)')),
                ('price', models.FloatField(default=100.0, verbose_name='Текущая цена')),
                ('last_tick_at', models.DateTimeField(verbose_name='Время последнего тика')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Время тика')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='core.asset', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Тик цены',
                'verbose_name_plural': 'Тики цен',
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Сторона')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена сделки')),
                ('total', models.FloatField(verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.asset', verbose_name='Актив')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('avg_price', models.FloatField(default=0.0, verbose_name='Средняя цена покупки')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='core.asset', verbose_name='Актив')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Портфель',
                'constraints': [models.UniqueConstraint(fields=('profile', 'asset'), name='unique_profile_asset')],
            },
        ),
    ]
