# Generated by Django 6.1 on 2026-08-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_more_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=8, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('crash', 'Крах'), ('hype', 'Хайп'), ('pump', 'Памп'), ('dump', 'Дамп')], max_length=10, verbose_name='Тип')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('multiplier', models.FloatField(verbose_name='Множитель цены')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.asset', verbose_name='Затронутый актив (None — весь рынок)')),
            ],
            options={
                'verbose_name': 'Рыночное событие',
                'verbose_name_plural': 'Рыночные события',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='core.achievement', verbose_name='Достижение')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'constraints': [models.UniqueConstraint(fields=('profile', 'achievement'), name='unique_profile_achievement')],
            },
        ),
    ]
